config/routes.rb
Planning::Application.routes.draw do

  devise_for :users

  resources :planning_apps do
    collection do
       get :search
    end
  end

  root 'planning_apps#welcome'

end

app/models/agent_name.rb
class AgentName < ActiveRecord::Base

  has_many :planning_apps

  validates :name, uniqueness: true

end

app/models/app_category.rb
class AppCategory < ActiveRecord::Base

  has_many :planning_apps

  validates :code, uniqueness: true

end

app/models/app_constraint.rb
class AppConstraint < ActiveRecord::Base

  validates :description, uniqueness: true

end

app/models/app_postcode.rb
class AppPostcode < ActiveRecord::Base
end

app/models/app_road.rb
class AppRoad < ActiveRecord::Base
end

app/models/app_status.rb
class AppStatus < ActiveRecord::Base

  has_many :planning_apps

  validates :description, uniqueness: true

end

app/models/officer.rb
class Officer < ActiveRecord::Base

  has_many :planning_apps

  validates :code, uniqueness: true

end

app/models/parish.rb
class Parish < ActiveRecord::Base

  has_many :planning_apps

  validates :name, uniqueness: true

end

app/models/planning_app.rb
class PlanningApp < ActiveRecord::Base

  belongs_to :app_status

  validates :reference, presence: true, uniqueness: true

  def details_url
    "https://www.mygov.je//Planning/Pages/PlanningApplicationDetail.aspx?s=1&r=#{reference}"
  end

  search_syntax do # for dusen 'Google-like' search
    search_by :text do |scope, phrases|
      columns = [:description]
      scope.where_like(columns => phrases)
    end
  end

end # of class

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/planning_apps_controller.rb
class PlanningAppsController < ApplicationController

  before_action :authenticate_user!, except: [:welcome]

  def welcome
  end

  def search
    @planning_apps = PlanningApp.search(params[:query]) # search is dusen method
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/planning_apps_helper.rb
module PlanningAppsHelper
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Zurb Foundation
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert-box round #{name == :notice ? "success" : "alert"}", "data-alert" => ""}
      = content_tag :div, msg
      %a.close{:href => "#"} &times;

app/views/layouts/_navigation.html.haml
-# navigation styled for Zurb Foundation 5
-# the syntax for data-topbar may need to change for Zurb Foundation 5
%nav.top-bar{"data-topbar" => true}
  %ul.title-area
    %li.name
      = link_to 'Home', root_path
    %li.toggle-topbar.menu-icon
      %a{:href => "#"}
        %span Menu
  .top-bar-section
    %ul.left
      = render 'layouts/navigation_links'
      = form_tag(search_planning_apps_path, method: :get) do
        = text_field_tag :query, nil, placeholder: 'Search applications'
        = submit_tag 'Search', class: 'alert button expand', id: 'search'
    %ul.hmenu.right
      = render 'devise/menu/registration_items'
      = render 'devise/menu/login_items'

app/views/layouts/_navigation_links.html.haml
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Dusen Test'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Dusen Test'}"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    -# Modernizr is required for Zurb Foundation
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/planning_apps/_planning_app.html.haml
%app
= link_to planning_app.reference, planning_app.details_url
= planning_app.description.truncate(150)
%br

app/views/planning_apps/search.html.haml
%h1 Search Results
= render @planning_apps

app/views/planning_apps/welcome.html.haml
%h1 Welcome to the site
%h2
  = "please login to continue" unless current_user